# Generated by Django 3.1.3 on 2020-11-05 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20201103_1544'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='user_id',
        ),
        migrations.AddField(
            model_name='article',
            name='create_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
